# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mxconsole/protobuf/__init__.py

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mxconsole/protobuf/__init__.py',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1emxconsole/protobuf/__init__.py')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





# @@protoc_insertion_point(module_scope)
